### ISSUE TITLE
podlinkuj te kafelki

### ISSUE THREAD

**Issue by 84lukaszkaminski** [palkak/dashboard#6]
https://github.com/palkak/dashboard/blob/beb7b3ac6aa2872d1081b1eb9253b774d39fadda/index.html#L97

**Comment by palkak** [comment]
Gdzie mają te kafelki przenosić na tę chwilę?

**Comment by 84lukaszkaminski** [comment]
do repozytorium projektu valor, do jiry (valor), witryny (valor) i jenkinsa

**Comment by palkak** [comment]
97 linia dotyczy innych elementów, niż te opisane wyżej. Błąd w zgłoszeniu.

**Comment by 84lukaszkaminski** [comment]
Oczywiście. Chodziło i sekcję 4. Punkt dla ciebie.
